### ISSUE TITLE
Long lines

### ISSUE THREAD

**Issue by Ashiidia** [PrincessRTFM/PositionalAssistant#1]
Lines get long, when you point camera outside near the center of the hitbox.
Current settings + video https://youtu.be/1X_i4WRgcoY
![image](https://user-images.githubusercontent.com/44702142/170778686-49e8307a-6bb1-4f63-9bc9-c7f789338383.png)

**Comment by VariableVixen** [comment]
...huh. That's interesting. I don't know how that's happening, actually. And I can't reproduce it on my system.

I can fix it, but at the cost of lines not drawing at _all_ if their end point is off the screen. I'll add a configuration option to toggle that. Gimme a few.
