### ISSUE TITLE
Minor/Typo: typo in settings panel

### ISSUE THREAD

**Issue by BlazingMarauder** [PrincessRTFM/PositionalAssistant#10]
For the Positional Assistant settings window;

`Always use the defined 'colowr' for the target circle?`

also inconsistent spelling of 'Color/Colour'

**Comment by VariableVixen** [comment]
The inconsistency is probably because I wrote _most_ of it, but then someone else PR'd the functionality for the "outer" circle, and I bet we have different spellings. I'll go look through it now.

**Comment by VariableVixen** [comment]
Fixed, it'll go live when the PAC has a chance to review it.
