### ISSUE TITLE
6.3 Update

### ISSUE THREAD

**Issue by tigurand** [PrincessRTFM/PositionalAssistant#2]
Hello, will you update this plugin for 6.3?
I use this a lot because I play with battle effects on and this helps me to determine enemy's direction.

**Comment by VariableVixen** [comment]
It's actually [already updated and waiting to be added to the official mainline repo](https://github.com/goatcorp/DalamudPluginsD17/pull/1077), and I'm just waiting on the reviewers to approve it. Unfortunately, I can't make that process any faster.
