### ISSUE TITLE
Guidelines: on

### ISSUE THREAD

**Issue by agitusera** [PrincessRTFM/PositionalAssistant#9]
can't turn off the screen clutter guidelines: on/off text at top right

**Comment by VariableVixen** [comment]
Those only pop up for a few seconds when you use the chat commands to change settings, then they vanish on their own. Is it really that annoying? I thought they were pretty unobtrusive when I added them.

**Comment by Slackluster** [comment]
The status added to the Server Info is actually permanently visible, it doesn't just appear when toggling the visibility. If that were the case, it'd be no issue.

![image](https://github.com/PrincessRTFM/PositionalAssistant/assets/29845810/ca72bf5d-cfc8-4335-a812-8072b81e7bce)

The ability to toggle the option through there might be neat for some users, but an option to toggle the display would be appreciated.

**Comment by VariableVixen** [comment]
Oh, _that_ part! You can actually toggle that in `/xlsettings`, in the Server Info Bar tab. Just uncheck the box labelled Positional Assistant. Maybe I should add a note on the settings window about that...

**Comment by Slackluster** [comment]
And yep, there it is! It makes sense for those settings to be consolidated there, but with how convoluted FFXIV mod menus can get, a note in PA's own settings probably can't hurt.

Thank you for the quick reply and the mod itself! I enjoy using it a lot. :)

**Comment by PandaCakes12321** [comment]
yeah might be a great idea too add a note too that.  it knocked out my ping/fps info heh

**Comment by VariableVixen** [comment]
Done, just waiting for the dalamud team to merge it
